# Generated by Django 5.0.2 on 2024-02-27 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('horror', 'Horror Movies: '), ('action', 'Action Movies: '), ('comedy', 'Comedy Movies: '), ('drama', 'Drama Movies: '), ('fantasy', 'Fantasy Movies: '), ('mystery', 'Mystery Movies: '), ('romance', 'Romance '), ('thriller', 'Thriller')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('actor', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='gallery')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.category')),
            ],
        ),
    ]
